---
title: 'Tarea con revisión'
labels: ['tarea', 'revisión']
---

## Descripción

Descripción de la tarea...

## Checklist
- [ ] 🚀 Implementación realizada
- [ ] 📚 Documentación actualizada / generada
- [ ] 📖 README actualizado (si aplica)
- [ ] ✅ Revisado y aprobado por otro desarrollador
